<?php

declare(strict_types=1);

namespace VincentNdegwa\EloquentTypegen\Support\Generators;

use Illuminate\Support\Str;
use VincentNdegwa\EloquentTypegen\Support\Metadata\FormRequestMetadata;

class FormRequestGenerator
{
    public function __construct(
        private readonly string $outputPath,
    ) {}

    /**
     * @param  FormRequestMetadata[]  $requests
     * @return array<string, string>
     */
    public function generate(array $requests): array
    {
        $files = [];

        // Requests go into a `requests/` subdirectory to avoid conflicting
        // with the model index.ts and model-helpers.ts files
        $basePath = $this->resolveOutputPath($this->outputPath).'/requests';

        foreach ($requests as $request) {
            $filePath = $basePath.'/'.$request->fileName;
            $files[$filePath] = $this->renderRequest($request);
        }

        if (! empty($requests) && (bool) config('typegen.generate_index', true)) {
            $files[$basePath.'/index.ts'] = $this->renderIndex($requests);
        }

        return $files;
    }

    private function resolveOutputPath(string $path): string
    {
        if (Str::startsWith($path, '/')) {
            return rtrim($path, '/');
        }

        return rtrim(base_path($path), '/');
    }

    private function renderRequest(FormRequestMetadata $request): string
    {
        $lines = [];
        $lines[] = '// This file is auto-generated by eloquent-typegen. Do not edit manually.';
        $lines[] = '';

        // Only import Nullable if any field actually needs it
        $needsNullable = collect($request->fields)->contains(fn ($f) => $f->nullable);
        if ($needsNullable) {
            $lines[] = "import type { Nullable } from '../model-helpers';";
            $lines[] = '';
        }

        $lines[] = "export interface {$request->interfaceName} {";

        foreach ($this->renderFields($request) as $fieldLine) {
            $lines[] = $fieldLine;
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /** @return string[] */
    private function renderFields(FormRequestMetadata $request): array
    {
        $lines = [];

        foreach ($request->fields as $field) {
            // optional (field?) = field may be absent from the payload
            $optionalMark = $field->optional ? '?' : '';

            // nullable = value can be null → wrap in Nullable<T>
            $type = $field->nullable ? "Nullable<{$field->type}>" : $field->type;

            // inline comment for conditional rules
            $comment = $field->comment ? "  // {$field->comment}" : '';

            $lines[] = "    {$field->name}{$optionalMark}: {$type};{$comment}";
        }

        return $lines;
    }

    /**
     * @param  FormRequestMetadata[]  $requests
     */
    private function renderIndex(array $requests): string
    {
        $lines = [
            '// This file is auto-generated by eloquent-typegen. Do not edit manually.',
            '',
        ];

        foreach ($requests as $request) {
            $file = Str::replaceLast('.ts', '', $request->fileName);
            $lines[] = "export type { {$request->interfaceName} } from './{$file}';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
