<?php

declare(strict_types=1);

namespace VincentNdegwa\EloquentTypegen\Support\Generators;

use Illuminate\Support\Str;
use VincentNdegwa\EloquentTypegen\Support\Metadata\ModelMetadata;
use VincentNdegwa\EloquentTypegen\Support\Metadata\ResourceMetadata;

class ResourceGenerator
{
    public function __construct(
        private readonly string $outputPath,
        /** @var array<string, ModelMetadata> */
        private readonly array $modelMap = [], // interfaceName => ModelMetadata
    ) {}

    /**
     * @param  ResourceMetadata[]  $resources
     * @return array<string, string>
     */
    public function generate(array $resources): array
    {
        $files = [];
        $resourceMap = $this->buildResourceMap($resources);

        // Output to the configured path directly (command adds /resources suffix)
        $basePath = $this->resolveOutputPath($this->outputPath);

        foreach ($resources as $resource) {
            $filePath = $basePath.'/'.$resource->fileName;
            $files[$filePath] = $this->renderResource($resource, $resourceMap);
        }

        if (! empty($resources) && (bool) config('typegen.generate_index', true)) {
            $files[$basePath.'/index.ts'] = $this->renderIndex($resources);
        }

        return $files;
    }

    /**
     * @param  ResourceMetadata[]  $resources
     * @return array<string, string>
     */
    private function buildResourceMap(array $resources): array
    {
        $map = [];
        foreach ($resources as $resource) {
            $map[$resource->interfaceName] = Str::replaceLast('.ts', '', $resource->fileName);
        }

        return $map;
    }

    private function resolveOutputPath(string $path): string
    {
        if (Str::startsWith($path, '/')) {
            return rtrim($path, '/');
        }

        return rtrim(base_path($path), '/');
    }

    /**
     * @param  array<string, string>  $resourceMap
     */
    private function renderResource(ResourceMetadata $resource, array $resourceMap): string
    {
        $lines = [];
        $lines[] = '// This file is auto-generated by eloquent-typegen. Do not edit manually.';
        $lines[] = '';

        // Check if we can extend the related model
        $relatedModel = $resource->relatedModel;
        $modelExists = isset($this->modelMap[$relatedModel]);
        $extendsModel = false;

        if ($modelExists) {
            $modelFileName = Str::replaceLast('.ts', '', $this->modelMap[$relatedModel]->fileName);
            $lines[] = "import type { {$relatedModel} } from '../models/{$modelFileName}';";
            $extendsModel = true;
        }

        $imports = $this->collectImports($resource, $resourceMap);
        if (! empty($imports)) {
            foreach ($imports as $import) {
                $lines[] = $import;
            }
            $lines[] = '';
        }

        // Only import Nullable if any field actually needs it
        $needsNullable = collect($resource->fields)->contains(fn ($f) => $f->nullable);
        if ($needsNullable) {
            $lines[] = "import type { Nullable } from '../model-helpers';";
            $lines[] = '';
        }

        foreach ($resource->enums as $enum) {
            $lines[] = "export type {$enum->name} = {$enum->definition};";
        }

        if (! empty($resource->enums)) {
            $lines[] = '';
        }

        // Build the extends clause and determine which fields to omit
        $extendsClause = '';
        $omittedFields = [];
        $sharedFields = [];

        if ($extendsModel) {
            // Find fields that are different from the model (renamed, transformed, or new)
            $modelFields = $this->getModelFields($relatedModel ?? '');
            $resourceFieldNames = collect($resource->fields)->pluck('name')->toArray();

            // Fields in model but not in resource (should be omitted)
            foreach ($modelFields as $modelField) {
                if (! in_array($modelField, $resourceFieldNames, true)) {
                    $omittedFields[] = $modelField;
                }
            }

            // Fields in resource that match model names (don't need to redeclare)
            $sharedFields = array_intersect($resourceFieldNames, $modelFields);
            $uniqueFields = array_diff($resourceFieldNames, $sharedFields);

            if (! empty($omittedFields)) {
                $omitClause = "'".implode("', '", $omittedFields)."'";
                $extendsClause = " extends Omit<{$relatedModel}, {$omitClause}>";
            } else {
                $extendsClause = " extends {$relatedModel}";
            }
        }

        $lines[] = "export interface {$resource->interfaceName}{$extendsClause} {";

        // Only render fields that are unique to the resource (not in model)
        foreach ($this->renderFields($resource, $sharedFields) as $fieldLine) {
            $lines[] = $fieldLine;
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param  array<string>  $skipFields
     * @return array<string>
     */
    private function renderFields(ResourceMetadata $resource, array $skipFields = []): array
    {
        $lines = [];

        foreach ($resource->fields as $field) {
            // Skip fields that are shared with the model (inherited via extends)
            if (in_array($field->name, $skipFields, true)) {
                continue;
            }

            // optional (field?) = field may be absent from the response
            $optionalMark = $field->optional ? '?' : '';

            // nullable = value can be null → wrap in Nullable<T>
            $type = $field->nullable ? "Nullable<{$field->type}>" : $field->type;

            // inline comment for conditional rules
            $comment = $field->conditional ? "  // {$field->condition}" : '';

            $lines[] = "    {$field->name}{$optionalMark}: {$type};{$comment}";
        }

        return $lines;
    }

    /**
     * Get field names from model metadata.
     *
     * @return array<string>
     */
    private function getModelFields(string $modelName): array
    {
        $model = $this->modelMap[$modelName] ?? null;
        if ($model === null) {
            return [];
        }

        /** @var array<string> */
        return collect($model->fields)->pluck('name')->toArray();
    }

    /**
     * @param  array<string, string>  $resourceMap
     * @return array<string>
     */
    private function collectImports(ResourceMetadata $resource, array $resourceMap): array
    {
        $imports = [];
        $typeImports = [];

        foreach ($resource->fields as $field) {
            if ($field->nestedResource) {
                $typeName = $this->baseType($field->type);
                if (isset($resourceMap[$typeName]) && $typeName !== $resource->interfaceName) {
                    $typeImports[$typeName] = $resourceMap[$typeName];
                }
            }
        }

        if (empty($typeImports)) {
            return $imports;
        }

        $grouped = [];
        foreach ($typeImports as $type => $file) {
            $grouped[$file][] = $type;
        }

        foreach ($grouped as $file => $types) {
            sort($types);
            $imports[] = 'import type { '.implode(', ', $types)." } from './{$file}';";
        }

        return $imports;
    }

    private function baseType(string $type): string
    {
        return str_ends_with($type, '[]') ? substr($type, 0, -2) : $type;
    }

    /**
     * @param  ResourceMetadata[]  $resources
     */
    private function renderIndex(array $resources): string
    {
        $lines = [
            '// This file is auto-generated by eloquent-typegen. Do not edit manually.',
            '',
        ];

        foreach ($resources as $resource) {
            $file = Str::replaceLast('.ts', '', $resource->fileName);
            $lines[] = "export type { {$resource->interfaceName} } from './{$file}';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
