<?php

declare(strict_types=1);

namespace VincentNdegwa\EloquentTypegen\Support\Generators;

use Illuminate\Support\Str;
use VincentNdegwa\EloquentTypegen\Support\Metadata\ModelMetadata;

class TypeScriptGenerator
{
    public function __construct(
        private readonly string $outputPath,
        private readonly bool $includeRelations,
    ) {}

    /**
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    public function generate(array $models): array
    {
        $files = [];
        $modelMap = $this->buildModelMap($models);
        $basePath = $this->resolveOutputPath($this->outputPath);

        foreach ($models as $model) {
            $filePath = $basePath.'/'.$model->fileName;
            $files[$filePath] = $this->renderModel($model, $modelMap);
        }

        if ((bool) config('typegen.generate_helpers', true)) {
            $files[$basePath.'/model-helpers.ts'] = $this->renderHelpers();
        }

        if ((bool) config('typegen.generate_index', true)) {
            $files[$basePath.'/index.ts'] = $this->renderIndex($models);
        }

        return $files;
    }

    /**
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    private function buildModelMap(array $models): array
    {
        $map = [];
        foreach ($models as $model) {
            $map[$model->interfaceName] = Str::replaceLast('.ts', '', $model->fileName);
        }

        return $map;
    }

    private function resolveOutputPath(string $path): string
    {
        if (Str::startsWith($path, '/')) {
            return rtrim($path, '/');
        }

        return rtrim(base_path($path), '/');
    }

    /**
     * @param  array<string, string>  $modelMap
     */
    private function renderModel(ModelMetadata $model, array $modelMap): string
    {
        $lines = [];
        $lines[] = '// This file is auto-generated by eloquent-typegen. Do not edit manually.';
        $lines[] = '';

        $imports = $this->collectImports($model, $modelMap);
        if (! empty($imports)) {
            foreach ($imports as $import) {
                $lines[] = $import;
            }
            $lines[] = '';
        }

        foreach ($model->enums as $enum) {
            $lines[] = "export type {$enum->name} = {$enum->definition};";
        }

        if (! empty($model->enums)) {
            $lines[] = '';
        }

        // Generate base interface (without relationships)
        $lines[] = "export interface {$model->interfaceName}Base {";
        foreach ($this->renderFields($model, false) as $fieldLine) {
            $lines[] = $fieldLine;
        }
        $lines[] = '}';
        $lines[] = '';

        if ($this->includeRelations) {
            $lines[] = "export interface {$model->interfaceName} extends {$model->interfaceName}Base {";
            foreach ($model->relations as $relation) {
                $lines[] = $this->formatField($relation->name, $relation->type, false, false, true);
            }
            $lines[] = '}';
            $lines[] = '';
        }

        // Create/Update payloads always use Base interface (without relationships)
        $createPayload = $this->renderCreatePayload($model, "{$model->interfaceName}Base");
        $updatePayload = $this->renderUpdatePayload($model);

        $lines[] = $createPayload;
        $lines[] = $updatePayload;
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @return array<string>
     */
    private function renderFields(ModelMetadata $model, bool $includeRelations): array
    {
        $lines = [];

        foreach ($model->fields as $field) {
            $lines[] = $this->formatField($field->name, $field->type, $field->nullable, $field->readonly, $field->optional);
        }

        foreach ($model->accessors as $accessor) {
            $lines[] = $this->formatField($accessor->name, 'unknown', false, true, true);
        }

        if ($includeRelations) {
            foreach ($model->relations as $relation) {
                $lines[] = $this->formatField($relation->name, $relation->type, false, false, true);
            }
        }

        return $lines;
    }

    private function formatField(string $name, string $type, bool $nullable, bool $readonly, bool $optional): string
    {
        $flags = $readonly ? 'readonly ' : '';
        $optionalMark = $optional ? '?' : '';
        $finalType = $nullable ? "Nullable<{$type}>" : $type;

        return "    {$flags}{$name}{$optionalMark}: {$finalType};";
    }

    /**
     * @param  array<string, string>  $modelMap
     * @return array<string>
     */
    private function collectImports(ModelMetadata $model, array $modelMap): array
    {
        $imports = [];
        $needsNullable = false;
        $typeImports = [];

        foreach ($model->fields as $field) {
            if ($field->nullable) {
                $needsNullable = true;
            }
        }

        if ($this->includeRelations) {
            foreach ($model->relations as $relation) {
                $typeName = $this->baseType($relation->type);
                if (isset($modelMap[$typeName]) && $typeName !== $model->interfaceName) {
                    $typeImports[$typeName] = $modelMap[$typeName];
                }
            }
        }

        if ($needsNullable) {
            $imports[] = "import type { Nullable } from './model-helpers';";
        }

        if (empty($typeImports)) {
            return $imports;
        }

        $grouped = [];
        foreach ($typeImports as $type => $file) {
            $grouped[$file][] = $type;
        }

        foreach ($grouped as $file => $types) {
            sort($types);
            $imports[] = 'import type { '.implode(', ', $types)." } from './{$file}';";
        }

        return $imports;
    }

    private function baseType(string $type): string
    {
        return str_ends_with($type, '[]') ? substr($type, 0, -2) : $type;
    }

    private function renderCreatePayload(ModelMetadata $model, string $interfaceName): string
    {
        $omit = $this->payloadOmitFields($model);

        if (empty($omit)) {
            return "export type Create{$model->interfaceName}Payload = {$interfaceName};";
        }

        $fields = $this->formatOmitList($omit);

        return "export type Create{$model->interfaceName}Payload = Omit<{$interfaceName}, {$fields}>;";
    }

    private function renderUpdatePayload(ModelMetadata $model): string
    {
        return "export type Update{$model->interfaceName}Payload = Partial<Create{$model->interfaceName}Payload>;";
    }

    /**
     * @return string[]
     */
    private function payloadOmitFields(ModelMetadata $model): array
    {
        $omit = ['id', 'created_at', 'updated_at'];

        // Only omit deleted_at if it exists in the model (soft delete)
        if (collect($model->fields)->first(fn ($field) => $field->name === 'deleted_at')) {
            $omit[] = 'deleted_at';
        }

        foreach ($model->accessors as $accessor) {
            $omit[] = $accessor->name;
        }

        // Don't omit relations since payloads always use Base interface (without relationships)
        return array_values(array_unique($omit));
    }

    /**
     * @param  string[]  $fields
     */
    private function formatOmitList(array $fields): string
    {
        $quoted = array_map(static fn (string $field) => "'{$field}'", $fields);

        return implode(' | ', $quoted);
    }

    private function renderHelpers(): string
    {
        return implode("\n", [
            'export type Nullable<T> = T | null;',
            'export type ModelId = number;',
            'export interface Paginated<T> {',
            '    current_page: number;',
            '    data: T[];',
            '    first_page_url: string | null;',
            '    from: number | null;',
            '    last_page: number;',
            '    last_page_url: string | null;',
            '    links: PaginationLink[];',
            '    next_page_url: string | null;',
            '    path: string;',
            '    per_page: number;',
            '    prev_page_url: string | null;',
            '    to: number | null;',
            '    total: number;',
            '}',
            'export interface PaginationLink {',
            '    url: string | null;',
            '    label: string;',
            '    active: boolean;',
            '}',
            'export interface ApiError {',
            '    message: string;',
            '    errors?: Record<string, string[]>;',
            '}',
            '',
        ]);
    }

    /**
     * @param  ModelMetadata[]  $models
     */
    private function renderIndex(array $models): string
    {
        $lines = [];

        foreach ($models as $model) {
            $file = Str::replaceLast('.ts', '', $model->fileName);

            if ($this->includeRelations) {
                // Export both Base and full interface when include_relations is true
                $lines[] = "export type { {$model->interfaceName}Base, {$model->interfaceName}, Create{$model->interfaceName}Payload, Update{$model->interfaceName}Payload } from './{$file}';";
            } else {
                // Export only Base interface when include_relations is false
                $lines[] = "export type { {$model->interfaceName}Base, Create{$model->interfaceName}Payload, Update{$model->interfaceName}Payload } from './{$file}';";
            }
        }

        if ((bool) config('typegen.generate_helpers', true)) {
            $lines[] = "export type { Nullable, ModelId, Paginated, ApiError } from './model-helpers';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
