<?php

declare(strict_types=1);

namespace VincentNdegwa\EloquentTypegen\Support\Generators;

use Illuminate\Support\Str;
use VincentNdegwa\EloquentTypegen\Support\Metadata\EnumMetadata;
use VincentNdegwa\EloquentTypegen\Support\Metadata\ModelMetadata;

class ZodGenerator
{
    public function __construct(
        private readonly string $outputPath,
        private readonly bool $includeRelations,
        private readonly bool $generateIndex = true,
    ) {}

    /**
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    public function generate(array $models): array
    {
        $files = [];
        $modelMap = $this->buildModelMap($models);
        $basePath = $this->resolveOutputPath($this->outputPath);

        foreach ($models as $model) {
            // Output alongside the .ts file but with .zod.ts suffix
            $zodFileName = Str::replaceLast('.ts', '.zod.ts', $model->fileName);
            $filePath = $basePath.'/'.$zodFileName;
            $files[$filePath] = $this->renderModel($model, $modelMap);
        }

        if (! empty($models) && $this->generateIndex) {
            $files[$basePath.'/index.zod.ts'] = $this->renderIndex($models);
        }

        return $files;
    }

    /**
     * Maps interfaceName → zod file base name (without .ts)
     * e.g. 'User' => 'user.zod'
     *
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    private function buildModelMap(array $models): array
    {
        $map = [];
        foreach ($models as $model) {
            $zodFile = Str::replaceLast('.ts', '.zod', $model->fileName);
            $map[$model->interfaceName] = $zodFile;
        }

        return $map;
    }

    private function resolveOutputPath(string $path): string
    {
        if (Str::startsWith($path, '/')) {
            return rtrim($path, '/');
        }

        return rtrim(base_path($path), '/');
    }

    /**
     * @param  array<string, string>  $modelMap  interfaceName => zodFileBase
     */
    private function renderModel(ModelMetadata $model, array $modelMap): string
    {
        $lines = [];
        $lines[] = '// This file is auto-generated by eloquent-typegen. Do not edit manually.';
        $lines[] = '';
        $lines[] = "import { z } from 'zod';";

        // Import related schemas for relations
        $relatedImports = $this->collectRelationImports($model, $modelMap);
        foreach ($relatedImports as $import) {
            $lines[] = $import;
        }

        $lines[] = '';

        // Declare enum schemas before the model schema that references them
        foreach ($model->enums as $enum) {
            $lines[] = $this->renderEnumSchema($enum);
        }

        if (! empty($model->enums)) {
            $lines[] = '';
        }

        // Main schema
        $schemaName = $model->interfaceName.'Schema';
        $lines[] = "export const {$schemaName} = z.object({";

        foreach ($this->renderFields($model, $modelMap) as $fieldLine) {
            $lines[] = $fieldLine;
        }

        $lines[] = '});';
        $lines[] = '';

        // Inferred TypeScript type from schema
        $lines[] = "export type {$model->interfaceName} = z.infer<typeof {$schemaName}>;";
        $lines[] = '';

        // Payload schemas — mirrors what TypeScriptGenerator produces
        $lines[] = $this->renderCreateSchema($model);
        $lines[] = $this->renderUpdateSchema($model);
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Produces: export const UserRoleSchema = z.enum(['admin', 'editor', 'viewer']);
     * Handles both string-backed enums ('admin' | 'editor') and int-backed (1 | 0).
     */
    private function renderEnumSchema(EnumMetadata $enum): string
    {
        // definition is the TypeScript union, e.g. "'admin' | 'editor'" or "1 | 0"
        $parts = array_map('trim', explode('|', $enum->definition));
        $schemaName = $enum->name.'Schema';

        // Detect int enum — values have no surrounding quotes
        $isIntEnum = ! str_starts_with($parts[0], "'");

        if ($isIntEnum) {
            // z.union([z.literal(1), z.literal(0)])
            $literals = implode(', ', array_map(
                fn (string $v) => 'z.literal('.$v.')',
                $parts
            ));

            return "export const {$schemaName} = z.union([{$literals}]);";
        }

        // String enum — use z.enum([...]) which is more ergonomic
        $values = implode(', ', array_map(
            fn (string $v) => trim($v), // keep the surrounding quotes from definition
            $parts
        ));

        return "export const {$schemaName} = z.enum([{$values}]);";
    }

    /**
     * @param  array<string, string>  $modelMap
     * @return string[]
     */
    private function renderFields(ModelMetadata $model, array $modelMap): array
    {
        $lines = [];
        $enumNames = array_map(fn ($e) => $e->name, $model->enums);

        foreach ($model->fields as $field) {
            $zodType = $this->typeToZod($field->type, $enumNames, $modelMap);

            if ($field->nullable) {
                $zodType .= '.nullable()';
            }

            if ($field->optional) {
                $zodType .= '.optional()';
            }

            $lines[] = "    {$field->name}: {$zodType},";
        }

        // Accessors — always unknown, always optional
        foreach ($model->accessors as $accessor) {
            $lines[] = "    {$accessor->name}: z.unknown().optional(),";
        }

        // Relations — optional since they're only present when eager-loaded
        if ($this->includeRelations) {
            foreach ($model->relations as $relation) {
                $zodType = $this->relationToZod($relation->type, $modelMap);
                $lines[] = "    {$relation->name}: {$zodType}.optional(),";
            }
        }

        return $lines;
    }

    /**
     * Convert a TypeScript type string back to a Zod expression.
     *
     * @param  string[]  $enumNames  enum names defined on this model
     * @param  array<string, string>  $modelMap
     */
    private function typeToZod(string $type, array $enumNames, array $modelMap): string
    {
        // Enum type — reference the already-declared schema
        if (in_array($type, $enumNames, true)) {
            return $type.'Schema';
        }

        // Related model type (single, e.g. 'Post') — use z.lazy for circular safety
        if (isset($modelMap[$type])) {
            return "z.lazy(() => {$type}Schema)";
        }

        // Array of related model (e.g. 'Post[]')
        if (str_ends_with($type, '[]')) {
            $base = substr($type, 0, -2);
            if (isset($modelMap[$base])) {
                return "z.array(z.lazy(() => {$base}Schema))";
            }
        }

        return match ($type) {
            'number' => 'z.number()',
            'string' => 'z.string()',
            'boolean' => 'z.boolean()',
            // date_type:'string' produces 'string' — covered above
            // date_type:'Date' produces 'Date' — handle explicitly
            'Date' => 'z.coerce.date()',
            // json/array casts
            'Record<string, unknown>' => 'z.record(z.string(), z.unknown())',
            'unknown[]' => 'z.array(z.unknown())',
            'unknown' => 'z.unknown()',
            default => 'z.unknown()',
        };
    }

    /**
     * Convert a relation type string (e.g. 'Post' or 'Post[]') to a Zod expression.
     *
     * @param  array<string, string>  $modelMap
     */
    private function relationToZod(string $type, array $modelMap): string
    {
        // Array relation e.g. 'Post[]'
        if (str_ends_with($type, '[]')) {
            $base = substr($type, 0, -2);

            if (isset($modelMap[$base])) {
                return "z.array(z.lazy(() => {$base}Schema))";
            }

            return 'z.array(z.unknown())';
        }

        // Single relation e.g. 'Post'
        if (isset($modelMap[$type])) {
            return "z.lazy(() => {$type}Schema)";
        }

        // MorphTo or unknown relation
        return 'z.unknown()';
    }

    /**
     * Build import statements for schemas of related models referenced in relations.
     *
     * @param  array<string, string>  $modelMap  interfaceName => zodFileBase
     * @return string[]
     */
    private function collectRelationImports(ModelMetadata $model, array $modelMap): array
    {
        if (! $this->includeRelations) {
            return [];
        }

        $imports = [];
        $seen = [];

        foreach ($model->relations as $relation) {
            $base = str_ends_with($relation->type, '[]')
                ? substr($relation->type, 0, -2)
                : $relation->type;

            // Don't import yourself (self-referential relations like parentQuote)
            if ($base === $model->interfaceName) {
                continue;
            }

            if (! isset($modelMap[$base]) || isset($seen[$base])) {
                continue;
            }

            $seen[$base] = true;
            $schemaName = $base.'Schema';
            $file = $modelMap[$base]; // e.g. 'post.zod'
            $imports[] = "import { {$schemaName} } from './{$file}';";
        }

        sort($imports);

        return $imports;
    }

    /**
     * CreateSchema omits system-managed fields and relations.
     * Mirrors CreateModelPayload from TypeScriptGenerator.
     */
    private function renderCreateSchema(ModelMetadata $model): string
    {
        $omit = ['id', 'created_at', 'updated_at', 'deleted_at'];

        foreach ($model->accessors as $accessor) {
            $omit[] = $accessor->name;
        }

        foreach ($model->relations as $relation) {
            $omit[] = $relation->name;
        }

        $omitStr = implode(', ', array_map(fn ($f) => "{$f}: true", array_unique($omit)));
        $schemaName = $model->interfaceName.'Schema';
        $createName = 'Create'.$model->interfaceName.'Schema';

        return "export const {$createName} = {$schemaName}.omit({ {$omitStr} });";
    }

    /**
     * UpdateSchema is the Create schema made fully partial.
     * Mirrors UpdateModelPayload from TypeScriptGenerator.
     */
    private function renderUpdateSchema(ModelMetadata $model): string
    {
        $createName = 'Create'.$model->interfaceName.'Schema';
        $updateName = 'Update'.$model->interfaceName.'Schema';

        return "export const {$updateName} = {$createName}.partial();";
    }

    /**
     * Generate an index.zod.ts barrel file that re-exports all schemas.
     *
     * @param  ModelMetadata[]  $models
     */
    private function renderIndex(array $models): string
    {
        $lines = [
            '// This file is auto-generated by eloquent-typegen. Do not edit manually.',
            '',
        ];

        foreach ($models as $model) {
            $schemaName = $model->interfaceName.'Schema';
            $createName = 'Create'.$model->interfaceName.'Schema';
            $updateName = 'Update'.$model->interfaceName.'Schema';
            $zodFile = Str::replaceLast('.ts', '.zod', $model->fileName);

            $lines[] = "export type { {$schemaName}, {$createName}, {$updateName} } from './{$zodFile}';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
