<?php

declare(strict_types=1);

namespace VincentNdegwa\EloquentTypegen\Support\Generators;

use Illuminate\Support\Str;
use VincentNdegwa\EloquentTypegen\Support\Metadata\EnumMetadata;
use VincentNdegwa\EloquentTypegen\Support\Metadata\FieldMetadata;
use VincentNdegwa\EloquentTypegen\Support\Metadata\ModelMetadata;

class ZodGenerator
{
    public function __construct(
        private readonly string $outputPath,
        private readonly bool $includeRelations,
        private readonly bool $generateIndex = true,
    ) {}

    /**
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    public function generate(array $models): array
    {
        $files = [];
        $modelMap = $this->buildModelMap($models);
        $basePath = $this->resolveOutputPath($this->outputPath);

        foreach ($models as $model) {
            // Output alongside the .ts file but with .zod.ts suffix
            $zodFileName = Str::replaceLast('.ts', '.zod.ts', $model->fileName);
            $filePath = $basePath.'/'.$zodFileName;
            $files[$filePath] = $this->renderModel($model, $modelMap);
        }

        if (! empty($models) && $this->generateIndex) {
            $files[$basePath.'/index.zod.ts'] = $this->renderIndex($models);
        }

        return $files;
    }

    /**
     * Maps interfaceName → zod file base name (without .ts)
     * e.g. 'User' => 'user.zod'
     *
     * @param  ModelMetadata[]  $models
     * @return array<string, string>
     */
    private function buildModelMap(array $models): array
    {
        $map = [];
        foreach ($models as $model) {
            $zodFile = Str::replaceLast('.ts', '.zod', $model->fileName);
            $map[$model->interfaceName] = $zodFile;
        }

        return $map;
    }

    private function resolveOutputPath(string $path): string
    {
        if (Str::startsWith($path, '/')) {
            return rtrim($path, '/');
        }

        return rtrim(base_path($path), '/');
    }

    /**
     * @param  array<string, string>  $modelMap  interfaceName => zodFileBase
     */
    private function renderModel(ModelMetadata $model, array $modelMap): string
    {
        $lines = [];
        $lines[] = '// This file is auto-generated by eloquent-typegen. Do not edit manually.';
        $lines[] = '';
        $lines[] = "import { z } from 'zod';";

        $relatedImports = $this->collectRelationImports($model, $modelMap);
        foreach ($relatedImports as $import) {
            $lines[] = $import;
        }

        $typeImports = $this->collectTypeImports($model, $modelMap);
        foreach ($typeImports as $import) {
            $lines[] = $import;
        }

        $lines[] = '';

        foreach ($model->enums as $enum) {
            $lines[] = $this->renderEnumSchema($enum);
        }

        if (! empty($model->enums)) {
            $lines[] = '';
        }

        $rawSchemaName = 'Raw'.$model->interfaceName.'Schema';
        $lines[] = "const {$rawSchemaName} = z.object({";

        foreach ($this->renderFields($model, $modelMap) as $fieldLine) {
            $lines[] = $fieldLine;
        }

        $lines[] = '});';
        $lines[] = '';

        $lines[] = $this->renderCreateSchema($model, $rawSchemaName);
        $lines[] = $this->renderUpdateSchema($model);
        $lines[] = '';

        $schemaName = $model->interfaceName.'Schema';
        if ($this->includeRelations) {
            $lines[] = "export const {$schemaName} = {$rawSchemaName} as z.ZodType<{$model->interfaceName}>;";
        } else {
            $lines[] = "export const {$schemaName} = {$rawSchemaName} as z.ZodType<{$model->interfaceName}Base>;";
        }
        $lines[] = '';

        if ($this->includeRelations) {
            $lines[] = "export type {$model->interfaceName} = {$model->interfaceName}Model;";
        } else {
            $lines[] = "export type {$model->interfaceName} = {$model->interfaceName}Base;";
        }
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Produces: export const UserRoleSchema = z.enum(['admin', 'editor', 'viewer']);
     */
    private function renderEnumSchema(EnumMetadata $enum): string
    {
        $definition = $enum->definition;
        $schemaName = $enum->name.'Schema';

        if (str_contains($definition, '|')) {
            $parts = explode('|', $definition);

            if (str_contains($definition, "'")) {
                $literals = implode(', ', array_map(
                    fn (string $v) => trim($v),
                    $parts
                ));

                return "export const {$schemaName} = z.enum([{$literals}]);";
            }

            $literals = implode(', ', array_map(
                fn (string $v) => 'z.literal('.trim($v).')',
                $parts
            ));

            return "export const {$schemaName} = z.union([{$literals}]);";
        }

        return "export const {$schemaName} = z.enum([{$definition}]);";
    }

    /**
     * @param  array<string, string>  $modelMap
     * @return string[]
     */
    private function renderFields(ModelMetadata $model, array $modelMap): array
    {
        $lines = [];
        $enumNames = array_map(fn ($e) => $e->name, $model->enums);

        foreach ($model->fields as $field) {
            $zodType = $this->typeToZod($field->type, $enumNames, $modelMap, $field);

            if ($field->nullable) {
                $zodType .= '.nullable()';
            }

            if ($field->optional) {
                $zodType .= '.optional()';
            }

            $lines[] = "    {$field->name}: {$zodType},";
        }

        foreach ($model->accessors as $accessor) {
            $lines[] = "    {$accessor->name}: z.unknown().optional(),";
        }

        if ($this->includeRelations) {
            foreach ($model->relations as $relation) {
                $zodType = $this->relationToZod($relation->type, $modelMap);
                $lines[] = "    {$relation->name}: {$zodType},";
            }
        }

        return $lines;
    }

    /**
     * Convert a TypeScript type string back to a Zod expression.
     *
     * @param  string[]  $enumNames  enum names defined on this model
     * @param  array<string, string>  $modelMap
     */
    private function typeToZod(string $type, array $enumNames, array $modelMap, FieldMetadata $field): string
    {
        if (in_array($type, $enumNames, true)) {
            return $type.'Schema';
        }

        if (isset($modelMap[$type])) {
            return "z.lazy(() => {$type}Schema).nullable() as z.ZodType<{$type} | null | undefined>";
        }

        if (str_ends_with($type, '[]')) {
            $base = substr($type, 0, -2);
            if (isset($modelMap[$base])) {
                return "z.array(z.lazy(() => {$base}Schema) as z.ZodType<{$base}>) as z.ZodType<{$base}[] | undefined>";
            }
        }

        $zodType = match ($type) {
            'number' => 'z.number()',
            'string' => 'z.string()',
            'boolean' => 'z.boolean()',
            'Date' => 'z.coerce.date()',
            'Record<string, unknown>' => 'z.record(z.string(), z.unknown())',
            'unknown[]' => 'z.array(z.unknown())',
            'unknown' => 'z.unknown()',
            default => 'z.unknown()',
        };

        return $this->applyConstraints($zodType, $field);
    }

    private function applyConstraints(string $zodType, FieldMetadata $field): string
    {
        if ($field->unsigned) {
            $zodType .= '.int().positive()';
        }

        if ($field->min !== null) {
            $zodType .= ".min({$field->min})";
        }

        if ($field->max !== null) {
            $zodType .= ".max({$field->max})";
        }

        return $zodType;
    }

    /**
     * Convert a relation type string (e.g. 'Post' or 'Post[]') to a Zod expression.
     *
     * @param  array<string, string>  $modelMap
     */
    private function relationToZod(string $type, array $modelMap): string
    {
        // Array relation e.g. 'Post[]'
        if (str_ends_with($type, '[]')) {
            $base = substr($type, 0, -2);

            if (isset($modelMap[$base])) {
                return "z.array(z.lazy(() => {$base}Schema) as z.ZodType<{$base}>) as z.ZodType<{$base}[] | undefined>";
            }

            return 'z.array(z.unknown())';
        }

        // Single relation e.g. 'Post'
        if (isset($modelMap[$type])) {
            return "z.lazy(() => {$type}Schema).nullable() as z.ZodType<{$type} | null | undefined>";
        }

        // MorphTo or unknown relation
        return 'z.unknown()';
    }

    /**
     * Build import statements for types from TypeScript files.
     *
     * @param  array<string, string>  $modelMap  interfaceName => zodFileBase
     * @return string[]
     */
    private function collectTypeImports(ModelMetadata $model, array $modelMap): array
    {
        if (! $this->includeRelations) {
            // When not including relations, import the base type
            return ["import type { {$model->interfaceName}Base } from './{$model->fileName}';"];
        }

        $imports = [];
        $seen = [];

        foreach ($model->relations as $relation) {
            $base = str_ends_with($relation->type, '[]')
                ? substr($relation->type, 0, -2)
                : $relation->type;

            // Don't import yourself (self-referential relations like parentQuote)
            if ($base === $model->interfaceName) {
                continue;
            }

            if (! isset($modelMap[$base]) || isset($seen[$base])) {
                continue;
            }

            $seen[$base] = true;
            $tsFile = $modelMap[$base]; // e.g. 'post'
            $imports[] = "import type { {$base} } from './{$tsFile}';";
        }

        // Import the full type for the current model
        $tsFile = Str::replaceLast('.ts', '', $model->fileName);
        $tsFile = Str::replaceLast('.zod', '', $tsFile);
        $imports[] = "import { {$model->interfaceName} as {$model->interfaceName}Model } from './{$tsFile}';";

        sort($imports);

        return $imports;
    }

    /**
     * Build import statements for schemas of related models referenced in relations.
     *
     * @param  array<string, string>  $modelMap  interfaceName => zodFileBase
     * @return string[]
     */
    private function collectRelationImports(ModelMetadata $model, array $modelMap): array
    {
        if (! $this->includeRelations) {
            return [];
        }

        $imports = [];
        $seen = [];

        foreach ($model->relations as $relation) {
            $base = str_ends_with($relation->type, '[]')
                ? substr($relation->type, 0, -2)
                : $relation->type;

            // Don't import yourself (self-referential relations like parentQuote)
            if ($base === $model->interfaceName) {
                continue;
            }

            if (! isset($modelMap[$base]) || isset($seen[$base])) {
                continue;
            }

            $seen[$base] = true;
            $schemaName = $base.'Schema';
            $file = $modelMap[$base]; // e.g. 'post.zod'
            $imports[] = "import { {$schemaName} } from './{$file}';";
        }

        sort($imports);

        return $imports;
    }

    private function renderCreateSchema(ModelMetadata $model, string $rawSchemaName): string
    {
        $omit = [];

        if (collect($model->fields)->first(fn ($field) => $field->name === 'id')) {
            $omit[] = 'id';
        }

        if (collect($model->fields)->first(fn ($field) => $field->name === 'created_at')) {
            $omit[] = 'created_at';
        }

        if (collect($model->fields)->first(fn ($field) => $field->name === 'updated_at')) {
            $omit[] = 'updated_at';
        }

        if (collect($model->fields)->first(fn ($field) => $field->name === 'deleted_at')) {
            $omit[] = 'deleted_at';
        }

        foreach ($model->accessors as $accessor) {
            $omit[] = $accessor->name;
        }

        $omitStr = implode(', ', array_map(fn ($f) => "{$f}: true", array_unique($omit)));
        $createName = 'Create'.$model->interfaceName.'Schema';

        if (empty($omit)) {
            return "export const {$createName} = {$rawSchemaName};";
        }

        return "export const {$createName} = {$rawSchemaName}.omit({ {$omitStr} });";
    }

    private function renderUpdateSchema(ModelMetadata $model): string
    {
        $createName = 'Create'.$model->interfaceName.'Schema';
        $updateName = 'Update'.$model->interfaceName.'Schema';

        return "export const {$updateName} = {$createName}.partial();";
    }

    /**
     * Generate an index.zod.ts barrel file that re-exports all schemas.
     *
     * @param  ModelMetadata[]  $models
     */
    private function renderIndex(array $models): string
    {
        $lines = [
            '// This file is auto-generated by eloquent-typegen. Do not edit manually.',
            '',
        ];

        foreach ($models as $model) {
            $schemaName = $model->interfaceName.'Schema';
            $createName = 'Create'.$model->interfaceName.'Schema';
            $updateName = 'Update'.$model->interfaceName.'Schema';
            $zodFile = Str::replaceLast('.ts', '.zod', $model->fileName);

            $lines[] = "export type { {$schemaName}, {$createName}, {$updateName} } from './{$zodFile}';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
